name: "health up"

on: 
  schedule: 
    - cron:  '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    

    steps:
    - uses: actions/checkout@v2
    - name: Use aaa青云版.js
    - uses: actions/setup-node@v2
    - run: 乐园.sh
